version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
      - certbot-etc:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - wordpress
      - certbot
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress_app
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - wordpress_network

  db:
    image: mariadb:latest
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d  # Auto-executes SQL scripts on startup
    networks:
      - wordpress_network

  redis:
    image: redis:alpine
    container_name: wordpress_redis
    networks:
      - wordpress_network

  backup:
    build: ./backup
    container_name: wordpress_backup
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - wordpress_network

  adminer:
    image: adminer
    container_name: wordpress_db_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:
  certbot-etc:

networks:
  wordpress_network:
    driver: bridge